# Generated by Django 3.0.5 on 2021-10-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=50000)),
                ('email', models.CharField(max_length=200)),
                ('Contact_No', models.IntegerField(max_length=12)),
            ],
        ),
    ]
