# Generated by Django 3.0.5 on 2021-11-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.CharField(default=1, max_length=80000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Contact_No',
            field=models.IntegerField(max_length=10),
        ),
    ]
